name: Cypress

on:

  push:
    branches: [main]

  pull_request:

permissions:

  contents: read

jobs:

  tests:
    name: Cypress Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          # @todo uncomment when workflow is finalized
          # - '7.4'
          # - '8.0'
          # - '8.1'
          - '8.2'
        wordpress:
          - 'latest'
        # @todo uncomment when workflow is finalized
        # include:
        #   - php: '7.4'
        #     wordpress: '5.5'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Prepare WP environment overrides
        run: |
          if [[ ${{ matrix.wordpress }} == "latest" ]]; then
            echo "{ \"phpVersion\": \"${{ matrix.php }}\" }" > .wp-env.override.json
          else
            echo "{ \"core\": \"WordPress/WordPress#${{ matrix.wordpress }}\", \"phpVersion\": \"${{ matrix.php }}\" }" > .wp-env.override.json
          fi

      - name: Start WP environment
        run: wp-env/prepare.sh

      - name: Run e2e tests
        run: npx cypress run

      - name: Upload Cypress artifacts on failure
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: cypress-artifact
          retention-days: 2
          path: |
            tests/cypress/screenshots/
            tests/cypress/videos/
